### ISSUE TITLE
Regarding test_audio_path

### ISSUE THREAD

**Issue by SreeramGanji** [JRMeyer/easy-kaldi#2]
Hi Josh! 
Thanks a lot for creating this wonderful project.
I am a bit confused what the test_audio_path and train_audio_path folders need to contain exactly. You have described it as 'one-line text file containing absolute path to dir of audio files (eg. WAV) for testing'. So if i get this correctly, I only need to provide the path of the parent directory which contains all my train/test audio files ?
Also, then how do you link train/test transcripts to the corresponding audio files? because you are not using the conventional unique id to each audio that Kaldi uses, how do you know which sentence in train/test transcript links to which audio file? I am asking this because this would help me create the transcripts.train/test files correctly :)  

Looking forward to hearing from you.

**Comment by JRMeyer** [comment]
Hi @SreeramGanji ! 

You're correct with regards to `train_audio_path` and `test_audio_path`. To be explicit, they look like this on my machine:

```
josh@carbon:~$ cat train_audio_path 
/home/josh/data/audio/train
josh@carbon:~$ cat test_audio_path 
/home/josh/data/audio/test
```

The second part of your question should be resolved if you got the two `*_audio_path` files above correctly formatted.
