### ISSUE TITLE
ERROR : Audio files & transcripts mismatch 

### ISSUE THREAD

**Issue by kodamvenkatsai818** [JRMeyer/easy-kaldi#3]
hello Meyer,
i have created all the files what you described in readme file and i created the file exactly by soft links and i ran the command ./run_gmm.sh corpus 001, than data corpus and plp_corpus folders and transcripts in input_corpus have created, here i am getting the error  
local/prepare_audio_data.sh: looking for audio data in input_corpus/audio

####
####
i checked the wav in  audio folder in input corpus (corpus_as prefix)  and trasncripts in input corpus, they are same i.e i have 7 wav files and 7 texts of those 7 wav file ids prefix with corpus below is the snipshot of those files 
corpus_5030082_20180406174312.wav (in audios folder) 
below one is snipshot of transcripts file
corpus_2172253165_20180406172509-0000323-0000405 good afternoon sir
corpus_2172253165_20180406172509-0000496-0000678 hello good evening
corpus_2172253165_20180406172509-0000707-0000824 hello
corpus_2172253165_20180406172509-0000873-0000993 <unk> <unk>       

is the format is correct or should do any change?

thanks!!

**Comment by rakibsxyz** [comment]
hey kodamvenkatsai818 ! how did you solve this problem? i am getting the same error!Let me know please!

**Comment by vasudev-hv** [comment]
Transcripts file must contain the the audio file name without extension and transcription
eg:
corpus_5030082_20180406174312 good afternoon sir
