### ISSUE TITLE
Full Input Corpus 

### ISSUE THREAD

**Issue by RezowanTalukder** [JRMeyer/easy-kaldi#5]
If someone could upload a snap of full tree view of working recipe's Input Corpus will be the best help ever. Josh mayer's description for input corpus doesn't seem that clear.

**Comment by JRMeyer** [comment]
Hi Rezowan,

Here's the full tree of the input_corpus directory:

```
input_corpus/
├── lexicon_nosil.txt -> /data/corpus/lexicon/lexicon_nosil.txt
├── lexicon.txt -> /data/corpus/lexicon/lexicon.txt
├── task.arpabo -> /data/corpus/lm/corpus.arpabo
├── test_audio_path -> /data/corpus/audio/test_audio_path
├── train_audio_path -> /data/corpus/audio/train_audio_path
├── transcripts.test -> /data/corpus/audio/transcripts.test
└── transcripts.train -> /data/corpus/audio/transcripts.train
```

Which part are you confused on?

**Comment by RezowanTalukder** [comment]
Thanks for your email Josh !
I was getting some trouble to create input_sorpus directory and wan't
understanding where to keep those files so I commented there. If you can
give me a snap of tree view of a full recipe that would be great.

Thanks
Rezowan
University of Dhaka

**Comment by RezowanTalukder** [comment]
Hi Josh,
I am facing some problems in decoding dnn model based on your
website tutorial. one-best-hypothesis.txt file is been created with no
error log but contains only the utterance id from wav.scp means no expected
output. Can you halp or give any suggestions regarding this problem or
solution .

thanks in advance

Rezowan

**Comment by JRMeyer** [comment]
@RezowanTalukder -- this is a new question. Please make sure you are submitting issues with enough context so that people can respond.

take a look here for advice on submitting good github issues: https://silvuss.github.io/2018/12/01/tips-to-submit-a-good-issue-on-github.html
