### ISSUE TITLE
Getting no output

### ISSUE THREAD

**Issue by RezowanTalukder** [JRMeyer/easy-kaldi#6]
Hi Josh,
I am facing some problems in decoding dnn model based on your website tutorial. one-best hypothesis.txt file is been created with no
error log but contains only the utterance id from wav.scp means no expected output. Can you halp or give any suggestions regarding this problem or
solution .

thanks in advance

Rezowan

**Comment by JRMeyer** [comment]
Please detail steps you took, so I might be able to understand
