### ISSUE TITLE
Can you provide sample data for all the files that needs to be added in input_dir

### ISSUE THREAD

**Issue by vasudev-hv** [JRMeyer/easy-kaldi#7]
Having trouble creating all the required files and in right format. Please provide (or point me to) the sample files..

**Comment by JRMeyer** [comment]
hi, I think the instructions in the README are pretty clear... what are you having issues with?

**Comment by vasudev-hv** [comment]
Readme says I need to create lexicon_nosil.txt, lexicon.txt, task.arpabo, transcripts.train and other such files and says they are available in kaldi and links to [the official docs](http://kaldi-asr.org/doc/data_prep.html). I couldn't find most of the files there. Could you please point me where exactly the files are, if not what format are the files supposed to be. Pardon me if these are basic questions, I just started with kaldi.

**Comment by vasudev-hv** [comment]
@JRMeyer - I was able to create all the required files and produce a model.
But when I use the model to transcribe an audio file, I get empty string. Can you please check the command and let me know what I'm missing.. (or is there any other command to transcribe?)
![image](https://user-images.githubusercontent.com/14175304/88310999-fb350600-cd2d-11ea-9920-186c139fd9b3.png)

**Comment by vasudev-hv** [comment]
@JRMeyer - Could you please help me here? After creating the model, what are the next steps to transcribe audios?

**Comment by JRMeyer** [comment]
Hi there -- I see you're needing some help, but the github issues isn't the place to post these kinds of questions. I'd recommend you take a look around my blog which will have a lot of common answers you're looking for, and you can look into the comments sections for some discussion from other folks.

here's a post that's related to what you're asking: http://jrmeyer.github.io/asr/2017/01/10/Using-built-DNN-model-Kaldi.html

-josh
